// <auto-generated />
namespace Socialize.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_final_match : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_final_match));
        
        string IMigrationMetadata.Id
        {
            get { return "201705131219131_add_final_match"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
